import type { Scheme, Application, ProcessedDocument, TimelineStage } from '@/types';

// ─── Mock Schemes ─────────────────────────────────────────
export const MOCK_SCHEMES: Scheme[] = [
  {
    id: 'pm-kisan',
    name: 'PM Kisan Samman Nidhi',
    nameHi: 'पीएम किसान सम्मान निधि',
    description: 'Direct income support of ₹6,000 per year to farmer families.',
    descriptionHi: '₹6,000 प्रति वर्ष की सीधी आय सहायता किसान परिवारों को।',
    category: 'agriculture',
    ministry: 'Ministry of Agriculture',
    benefitAmount: 6000,
    benefitType: 'cash',
    eligibilityMatch: 95,
    requiredDocs: ['aadhaar', 'bank_passbook', 'ration_card'],
    eligibilityCriteria: [
      { label: 'Small/Marginal Farmer',  labelHi: 'लघु/सीमांत किसान', met: true,  value: 'Yes' },
      { label: 'Land Holding',           labelHi: 'भूमि स्वामित्व',    met: true,  value: '1.2 acres' },
      { label: 'Not a govt employee',    labelHi: 'सरकारी कर्मचारी नहीं', met: true,  value: 'Yes' },
      { label: 'Bank account linked',    labelHi: 'बैंक खाता जुड़ा है', met: false, value: 'Pending' },
    ],
    applicationUrl: 'https://pmkisan.gov.in',
    applicationCount: 12400,
    approvalRate: 87,
    avgApprovalDays: 14,
  },
  {
    id: 'pmay',
    name: 'PM Awas Yojana (Gramin)',
    nameHi: 'पीएम आवास योजना (ग्रामीण)',
    description: 'Housing assistance for rural poor to construct pucca houses.',
    descriptionHi: 'ग्रामीण गरीबों को पक्के मकान बनाने के लिए आवास सहायता।',
    category: 'housing',
    ministry: 'Ministry of Rural Development',
    benefitAmount: 130000,
    benefitType: 'subsidy',
    eligibilityMatch: 78,
    requiredDocs: ['aadhaar', 'ration_card', 'income_certificate'],
    eligibilityCriteria: [
      { label: 'BPL Category',    labelHi: 'बीपीएल श्रेणी',  met: true,  value: 'Yes' },
      { label: 'No Pucca House',  labelHi: 'पक्का मकान नहीं', met: true,  value: 'Confirmed' },
      { label: 'Annual Income',   labelHi: 'वार्षिक आय',     met: false, value: '₹80,000' },
    ],
    applicationCount: 5600,
    approvalRate: 72,
    avgApprovalDays: 45,
  },
  {
    id: 'nsp-scholarship',
    name: 'NSP Pre-Matric Scholarship',
    nameHi: 'एनएसपी प्री-मैट्रिक छात्रवृत्ति',
    description: 'Scholarship for minority students studying in Class 1 to 10.',
    descriptionHi: 'अल्पसंख्यक छात्रों के लिए छात्रवृत्ति जो कक्षा 1 से 10 में पढ़ रहे हैं।',
    category: 'education',
    ministry: 'Ministry of Minority Affairs',
    benefitAmount: 10000,
    benefitType: 'scholarship',
    deadline: new Date('2026-04-30'),
    eligibilityMatch: 90,
    requiredDocs: ['aadhaar', 'marksheet', 'income_certificate', 'caste_certificate'],
    eligibilityCriteria: [
      { label: 'Minority Community', labelHi: 'अल्पसंख्यक समुदाय', met: true,  value: 'Yes' },
      { label: 'Class 1-10',         labelHi: 'कक्षा 1-10',          met: true,  value: 'Class 8' },
      { label: 'Annual Income < 1L', labelHi: 'वार्षिक आय < 1 लाख', met: true,  value: '₹72,000' },
    ],
    applicationCount: 8900,
    approvalRate: 91,
    avgApprovalDays: 21,
  },
  {
    id: 'ayushman-bharat',
    name: 'Ayushman Bharat PMJAY',
    nameHi: 'आयुष्मान भारत पीएमजेएवाई',
    description: 'Health insurance coverage of ₹5 lakh per family per year.',
    descriptionHi: 'प्रति परिवार प्रति वर्ष ₹5 लाख का स्वास्थ्य बीमा।',
    category: 'healthcare',
    ministry: 'Ministry of Health',
    benefitAmount: 500000,
    benefitType: 'service',
    eligibilityMatch: 85,
    requiredDocs: ['aadhaar', 'ration_card'],
    eligibilityCriteria: [
      { label: 'SECC Database',  labelHi: 'एसईसीसी डेटाबेस', met: true, value: 'Registered' },
      { label: 'BPL/APL Status', labelHi: 'बीपीएल/एपीएल',    met: true, value: 'BPL' },
    ],
    applicationCount: 19200,
    approvalRate: 88,
    avgApprovalDays: 7,
  },
  {
    id: 'pm-ujjwala',
    name: 'PM Ujjwala Yojana',
    nameHi: 'पीएम उज्ज्वला योजना',
    description: 'Free LPG connections to women from BPL households.',
    descriptionHi: 'बीपीएल परिवारों की महिलाओं को मुफ़्त एलपीजी कनेक्शन।',
    category: 'women',
    ministry: 'Ministry of Petroleum',
    benefitType: 'goods',
    eligibilityMatch: 60,
    requiredDocs: ['aadhaar', 'ration_card'],
    eligibilityCriteria: [
      { label: 'BPL Household',   labelHi: 'बीपीएल परिवार',    met: true,  value: 'Yes' },
      { label: 'No existing LPG', labelHi: 'LPG कनेक्शन नहीं', met: false, value: 'Has connection' },
    ],
    applicationCount: 3400,
    approvalRate: 95,
    avgApprovalDays: 10,
  },
  {
    id: 'mnrega',
    name: 'MGNREGA Employment',
    nameHi: 'मनरेगा रोज़गार',
    description: '100 days of guaranteed rural employment at minimum wage.',
    descriptionHi: '100 दिनों का गारंटीकृत ग्रामीण रोज़गार न्यूनतम मज़दूरी पर।',
    category: 'employment',
    ministry: 'Ministry of Rural Development',
    benefitAmount: 24700,
    benefitType: 'cash',
    eligibilityMatch: 72,
    requiredDocs: ['aadhaar', 'ration_card', 'bank_passbook'],
    eligibilityCriteria: [
      { label: 'Rural Resident',    labelHi: 'ग्रामीण निवासी',  met: true,  value: 'Yes' },
      { label: 'Above 18 years',    labelHi: '18 वर्ष से अधिक', met: true,  value: '34 years' },
      { label: 'Job Card Holder',   labelHi: 'जॉब कार्ड धारक', met: false, value: 'Not registered' },
    ],
    applicationCount: 7100,
    approvalRate: 82,
    avgApprovalDays: 5,
  },
];

// ─── Mock Applications ────────────────────────────────────
const baseTimeline: TimelineStage[] = [
  { name: 'Submitted',     nameHi: 'जमा किया',     status: 'completed', date: new Date('2026-01-10'), description: 'Application submitted successfully', descriptionHi: 'आवेदन सफलतापूर्वक जमा किया गया' },
  { name: 'Document Verification', nameHi: 'दस्तावेज़ सत्यापन', status: 'completed', date: new Date('2026-01-12'), description: 'Documents verified', descriptionHi: 'दस्तावेज़ सत्यापित' },
  { name: 'Under Review',  nameHi: 'समीक्षा में',  status: 'current',   description: 'Application under review', descriptionHi: 'आवेदन की समीक्षा की जा रही है' },
  { name: 'Approval',      nameHi: 'अनुमोदन',      status: 'pending',   description: 'Awaiting approval decision', descriptionHi: 'अनुमोदन निर्णय की प्रतीक्षा' },
  { name: 'Disbursement',  nameHi: 'वितरण',         status: 'pending',   description: 'Amount will be disbursed', descriptionHi: 'राशि वितरित की जाएगी' },
];

export const MOCK_APPLICATIONS: Application[] = [
  {
    id: 'app-1',
    schemeId: 'pm-kisan',
    scheme: MOCK_SCHEMES[0],
    status: 'processing',
    submittedAt: new Date('2026-01-10'),
    updatedAt: new Date('2026-01-20'),
    acknowledgementNo: 'PMKISAN2026011012345',
    nextAction: 'Upload missing bank passbook',
    nextActionDeadline: new Date('2026-02-01'),
    timeline: baseTimeline,
    documents: [],
  },
  {
    id: 'app-2',
    schemeId: 'nsp-scholarship',
    scheme: MOCK_SCHEMES[2],
    status: 'approved',
    submittedAt: new Date('2025-12-01'),
    updatedAt: new Date('2025-12-22'),
    acknowledgementNo: 'NSP2025120154321',
    timeline: baseTimeline.map((s, i) => ({ ...s, status: i < 4 ? 'completed' : 'pending' }) as TimelineStage),
    documents: [],
  },
  {
    id: 'app-3',
    schemeId: 'ayushman-bharat',
    scheme: MOCK_SCHEMES[3],
    status: 'applied',
    submittedAt: new Date('2026-02-14'),
    updatedAt: new Date('2026-02-14'),
    acknowledgementNo: 'PMJAY2026021498765',
    timeline: [
      { ...baseTimeline[0], status: 'completed' },
      ...baseTimeline.slice(1).map(s => ({ ...s, status: 'pending' }) as TimelineStage),
    ],
    documents: [],
  },
];

// ─── Mock Documents ───────────────────────────────────────
export const MOCK_DOCUMENTS: ProcessedDocument[] = [
  {
    id: 'doc-1',
    type: 'aadhaar',
    filename: 'Aadhaar_Ramesh_Kumar.pdf',
    extractedData: { 'Name': 'Ramesh Kumar', 'DOB': '15/08/1990', 'Gender': 'Male', 'Aadhaar No': '1234 5678 9012' },
    confidence: 0.97,
    status: 'verified',
    uploadedAt: new Date('2025-11-20'),
    fileSize: 245000,
  },
  {
    id: 'doc-2',
    type: 'income_certificate',
    filename: 'Income_Certificate_2025.pdf',
    extractedData: { 'Name': 'Ramesh Kumar', 'Annual Income': '₹72,000', 'Year': '2024-25', 'Issued By': 'Tehsildar Lucknow' },
    confidence: 0.91,
    status: 'verified',
    uploadedAt: new Date('2025-12-05'),
    expiryDate: new Date('2026-12-05'),
    fileSize: 180000,
  },
  {
    id: 'doc-3',
    type: 'bank_passbook',
    filename: 'SBI_Passbook_Jan2026.jpg',
    extractedData: { 'Bank': 'SBI', 'Account No': 'XXXX1234', 'IFSC': 'SBIN0001234', 'Branch': 'Lucknow Main' },
    confidence: 0.72,
    status: 'verified',
    uploadedAt: new Date('2026-01-08'),
    fileSize: 420000,
  },
  {
    id: 'doc-4',
    type: 'marksheet',
    filename: 'Marksheet_Class8.jpg',
    extractedData: { 'Student': 'Aayush Kumar', 'Class': 'VIII', 'School': 'GPS Lucknow', 'Percentage': '78%' },
    confidence: 0.88,
    status: 'verified',
    uploadedAt: new Date('2026-01-15'),
    fileSize: 320000,
  },
];
