import type { Language, LanguageOption, SchemeCategory } from '@/types';

// ============================================================
// API Configuration
// ============================================================
export const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || 'https://api.civicbridge.in';
export const WS_BASE_URL = import.meta.env.VITE_WS_BASE_URL || 'wss://ws.civicbridge.in';

// ============================================================
// Languages
// ============================================================
export const LANGUAGES: LanguageOption[] = [
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', script: 'Devanagari' },
  { code: 'en', name: 'English', nativeName: 'English', script: 'Latin' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்', script: 'Tamil' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు', script: 'Telugu' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা', script: 'Bengali' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी', script: 'Devanagari' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી', script: 'Gujarati' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ', script: 'Kannada' },
  { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം', script: 'Malayalam' },
  { code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ', script: 'Gurmukhi' },
];

export const DEFAULT_LANGUAGE: Language = 'hi';

// ============================================================
// Scheme Category Colors & Labels
// ============================================================
export const CATEGORY_CONFIG: Record<SchemeCategory, { color: string; bg: string; icon: string; label: string; labelHi: string }> = {
  education: { color: '#3B82F6', bg: '#EFF6FF', icon: 'GraduationCap', label: 'Education', labelHi: 'शिक्षा' },
  health: { color: '#EF4444', bg: '#FEF2F2', icon: 'Heart', label: 'Health', labelHi: 'स्वास्थ्य' },
  welfare: { color: '#22C55E', bg: '#F0FDF4', icon: 'Users', label: 'Welfare', labelHi: 'कल्याण' },
  agriculture: { color: '#F59E0B', bg: '#FFFBEB', icon: 'Wheat', label: 'Agriculture', labelHi: 'कृषि' },
  pension: { color: '#8B5CF6', bg: '#F5F3FF', icon: 'Landmark', label: 'Pension', labelHi: 'पेंशन' },
  housing: { color: '#EC4899', bg: '#FDF2F8', icon: 'Home', label: 'Housing', labelHi: 'आवास' },
};

// ============================================================
// Document Type Config
// ============================================================
export const DOCUMENT_TYPES = {
  aadhaar: { label: 'Aadhaar Card', labelHi: 'आधार कार्ड', icon: 'CreditCard' },
  pan: { label: 'PAN Card', labelHi: 'पैन कार्ड', icon: 'CreditCard' },
  voter_id: { label: 'Voter ID', labelHi: 'मतदाता पहचान पत्र', icon: 'Vote' },
  ration_card: { label: 'Ration Card', labelHi: 'राशन कार्ड', icon: 'FileText' },
  income_cert: { label: 'Income Certificate', labelHi: 'आय प्रमाण पत्र', icon: 'FileCheck' },
  caste_cert: { label: 'Caste Certificate', labelHi: 'जाति प्रमाण पत्र', icon: 'FileCheck' },
  domicile: { label: 'Domicile Certificate', labelHi: 'अधिवास प्रमाण पत्र', icon: 'MapPin' },
  bank_passbook: { label: 'Bank Passbook', labelHi: 'बैंक पासबुक', icon: 'Building2' },
  photo: { label: 'Passport Photo', labelHi: 'पासपोर्ट फोटो', icon: 'Camera' },
  marksheet: { label: 'Marksheet', labelHi: 'अंकसूची', icon: 'BookOpen' },
  other: { label: 'Other Document', labelHi: 'अन्य दस्तावेज़', icon: 'File' },
} as const;

// ============================================================
// Translations (i18n)
// ============================================================
export const TRANSLATIONS: Record<string, Record<Language, string>> = {
  'app.title': { en: 'CivicBridge', hi: 'सिविकब्रिज', ta: 'சிவிக்பிரிட்ஜ்', te: 'సివిక్‌బ్రిడ్జ్', bn: 'সিভিকব্রিজ', mr: 'सिव्हिकब्रिज', gu: 'સિવિકબ્રિજ', kn: 'ಸಿವಿಕ್‌ಬ್ರಿಡ್ಜ್', ml: 'സിവിക്ബ്രിഡ്ജ്', pa: 'ਸਿਵਿਕਬ੍ਰਿਜ' },
  'app.tagline': { en: 'Apply in 5 minutes', hi: '5 मिनट में आवेदन', ta: '5 நிமிடத்தில் விண்ணப்பிக்கவும்', te: '5 నిమిషాల్లో దరఖాస్తు', bn: '5 মিনিটে আবেদন', mr: '5 मिनिटांत अर्ज करा', gu: '5 મિનિટમાં અરજી', kn: '5 ನಿಮಿಷಗಳಲ್ಲಿ ಅರ್ಜಿ', ml: '5 മിനിറ്റിൽ അപേക്ഷിക്കുക', pa: '5 ਮਿੰਟਾਂ ਵਿੱਚ ਅਰਜ਼ੀ' },
  'nav.home': { en: 'Home', hi: 'होम', ta: 'முகப்பு', te: 'హోమ్', bn: 'হোম', mr: 'मुख्यपृष्ठ', gu: 'હોમ', kn: 'ಮುಖಪುಟ', ml: 'ഹോം', pa: 'ਹੋਮ' },
  'nav.voice': { en: 'Voice', hi: 'आवाज़', ta: 'குரல்', te: 'వాయిస్', bn: 'ভয়েস', mr: 'आवाज', gu: 'અવાજ', kn: 'ಧ್ವನಿ', ml: 'ശബ്ദം', pa: 'ਆਵਾਜ਼' },
  'nav.documents': { en: 'Documents', hi: 'दस्तावेज़', ta: 'ஆவணங்கள்', te: 'పత్రాలు', bn: 'নথিপত্র', mr: 'दस्तऐवज', gu: 'દસ્તાવેજો', kn: 'ದಾಖಲೆಗಳು', ml: 'രേഖകൾ', pa: 'ਦਸਤਾਵੇਜ਼' },
  'nav.profile': { en: 'Profile', hi: 'प्रोफाइल', ta: 'சுயவிவரம்', te: 'ప్రొఫైల్', bn: 'প্রোফাইল', mr: 'प्रोफाइल', gu: 'પ્રોફાઈલ', kn: 'ಪ್ರೊಫೈಲ್', ml: 'പ്രൊഫൈൽ', pa: 'ਪ੍ਰੋਫਾਈਲ' },
  'voice.tap_to_speak': { en: 'Tap to speak', hi: 'बोलने के लिए टैप करें', ta: 'பேச தட்டவும்', te: 'మాట్లాడటానికి నొక్కండి', bn: 'কথা বলতে ট্যাপ করুন', mr: 'बोलण्यासाठी टॅप करा', gu: 'બોલવા માટે ટેપ કરો', kn: 'ಮಾತನಾಡಲು ಟ್ಯಾಪ್ ಮಾಡಿ', ml: 'സംസാരിക്കാൻ ടാപ്പ് ചെയ്യുക', pa: 'ਬੋਲਣ ਲਈ ਟੈਪ ਕਰੋ' },
  'voice.listening': { en: 'Listening...', hi: 'सुन रहा हूँ...', ta: 'கேட்கிறேன்...', te: 'వింటున్నాను...', bn: 'শুনছি...', mr: 'ऐकत आहे...', gu: 'સાંભળી રહ્યું છે...', kn: 'ಕೇಳುತ್ತಿದ್ದೇನೆ...', ml: 'കേൾക്കുന്നു...', pa: 'ਸੁਣ ਰਿਹਾ ਹਾਂ...' },
  'voice.processing': { en: 'Processing...', hi: 'प्रोसेसिंग...', ta: 'செயலாக்குகிறது...', te: 'ప్రాసెస్ చేస్తోంది...', bn: 'প্রসেসিং...', mr: 'प्रक्रिया सुरू...', gu: 'પ્રક્રિયા કરી રહ્યું છે...', kn: 'ಪ್ರಕ್ರಿಯೆ...', ml: 'പ്രോസസ്സ് ചെയ്യുന്നു...', pa: 'ਪ੍ਰੋਸੈਸਿੰਗ...' },
  'voice.speaking': { en: 'Speaking...', hi: 'बोल रहा हूँ...', ta: 'பேசுகிறேன்...', te: 'చెబుతున్నాను...', bn: 'বলছি...', mr: 'बोलत आहे...', gu: 'બોલી રહ્યું છે...', kn: 'ಹೇಳುತ್ತಿದ್ದೇನೆ...', ml: 'പറയുന്നു...', pa: 'ਬੋਲ ਰਿਹਾ ਹਾਂ...' },
  'home.greeting_morning': { en: 'Good Morning', hi: 'सुप्रभात', ta: 'காலை வணக்கம்', te: 'శుభోదయం', bn: 'সুপ্রভাত', mr: 'सुप्रभात', gu: 'સુપ્રભાત', kn: 'ಶುಭೋದಯ', ml: 'സുപ്രഭാതം', pa: 'ਸ਼ੁਭ ਸਵੇਰ' },
  'home.greeting_afternoon': { en: 'Good Afternoon', hi: 'नमस्कार', ta: 'மதிய வணக்கம்', te: 'శుభ మధ్యాహ్నం', bn: 'শুভ অপরাহ্ণ', mr: 'नमस्कार', gu: 'શુભ બપોર', kn: 'ಶುಭ ಮಧ್ಯಾಹ್ನ', ml: 'ശുഭ ഉച്ച', pa: 'ਸ਼ੁਭ ਦੁਪਹਿਰ' },
  'home.greeting_evening': { en: 'Good Evening', hi: 'शुभ संध्या', ta: 'மாலை வணக்கம்', te: 'శుభ సాయంత్రం', bn: 'শুভ সন্ধ্যা', mr: 'शुभ संध्याकाळ', gu: 'શુભ સાંજ', kn: 'ಶುಭ ಸಂಜೆ', ml: 'ശുഭ സന്ധ്യ', pa: 'ਸ਼ੁਭ ਸ਼ਾਮ' },
  'home.find_schemes': { en: 'Find Schemes', hi: 'योजनाएं खोजें', ta: 'திட்டங்களை கண்டறியுங்கள்', te: 'పథకాలు కనుగొనండి', bn: 'প্রকল্প খুঁজুন', mr: 'योजना शोधा', gu: 'યોજનાઓ શોધો', kn: 'ಯೋಜನೆಗಳನ್ನು ಹುಡುಕಿ', ml: 'പദ്ധതികൾ കണ്ടെത്തുക', pa: 'ਯੋਜਨਾਵਾਂ ਲੱਭੋ' },
  'home.my_applications': { en: 'My Applications', hi: 'मेरे आवेदन', ta: 'எனது விண்ணப்பங்கள்', te: 'నా దరఖాస్తులు', bn: 'আমার আবেদন', mr: 'माझे अर्ज', gu: 'મારી અરજીઓ', kn: 'ನನ್ನ ಅರ್ಜಿಗಳು', ml: 'എന്റെ അപേക്ഷകൾ', pa: 'ਮੇਰੀਆਂ ਅਰਜ਼ੀਆਂ' },
  'home.upload_documents': { en: 'Upload Documents', hi: 'दस्तावेज़ अपलोड', ta: 'ஆவணங்களை பதிவேற்றவும்', te: 'పత్రాలు అప్‌లోడ్', bn: 'নথি আপলোড', mr: 'दस्तऐवज अपलोड', gu: 'દસ્તાવેજો અપલોડ', kn: 'ದಾಖಲೆಗಳನ್ನು ಅಪ್‌ಲೋಡ್', ml: 'രേഖകൾ അപ്‌ലോഡ്', pa: 'ਦਸਤਾਵੇਜ਼ ਅੱਪਲੋਡ' },
  'home.get_help': { en: 'Get Help', hi: 'सहायता', ta: 'உதவி', te: 'సహాయం', bn: 'সাহায্য', mr: 'मदत', gu: 'મદદ', kn: 'ಸಹಾಯ', ml: 'സഹായം', pa: 'ਮਦਦ' },
  'schemes.search': { en: 'Search schemes...', hi: 'योजनाएं खोजें...', ta: 'திட்டங்களை தேடுங்கள்...', te: 'పథకాలు వెతకండి...', bn: 'প্রকল্প অনুসন্ধান...', mr: 'योजना शोधा...', gu: 'યોજનાઓ શોધો...', kn: 'ಯೋಜನೆಗಳನ್ನು ಹುಡುಕಿ...', ml: 'പദ്ധതികൾ തിരയുക...', pa: 'ਯੋਜਨਾਵਾਂ ਖੋਜੋ...' },
  'schemes.all': { en: 'All', hi: 'सभी', ta: 'அனைத்தும்', te: 'అన్నీ', bn: 'সকল', mr: 'सर्व', gu: 'બધા', kn: 'ಎಲ್ಲಾ', ml: 'എല്ലാം', pa: 'ਸਭ' },
  'schemes.apply_now': { en: 'Apply Now', hi: 'अभी आवेदन करें', ta: 'இப்போது விண்ணப்பிக்கவும்', te: 'ఇప్పుడు దరఖాస్తు చేయండి', bn: 'এখনই আবেদন করুন', mr: 'आता अर्ज करा', gu: 'હવે અરજી કરો', kn: 'ಈಗ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ', ml: 'ഇപ്പോൾ അപേക്ഷിക്കുക', pa: 'ਹੁਣੇ ਅਰਜ਼ੀ ਦਿਓ' },
  'schemes.per_year': { en: '/year', hi: '/वर्ष', ta: '/ஆண்டு', te: '/సంవత్సరం', bn: '/বছর', mr: '/वर्ष', gu: '/વર્ષ', kn: '/ವರ್ಷ', ml: '/വർഷം', pa: '/ਸਾਲ' },
  'schemes.per_month': { en: '/month', hi: '/माह', ta: '/மாதம்', te: '/నెల', bn: '/মাস', mr: '/महिना', gu: '/મહિનો', kn: '/ತಿಂಗಳು', ml: '/മാസം', pa: '/ਮਹੀਨਾ' },
  'schemes.one_time': { en: 'one-time', hi: 'एकमुश्त', ta: 'ஒரு முறை', te: 'ఒకసారి', bn: 'এককালীন', mr: 'एकदम', gu: 'એકવાર', kn: 'ಒಂದು ಬಾರಿ', ml: 'ഒറ്റത്തവണ', pa: 'ਇੱਕ ਵਾਰ' },
  'eligibility.perfect': { en: 'Perfect Match', hi: 'बिल्कुल सही', ta: 'சரியான பொருத்தம்', te: 'సరైన అనుకూలత', bn: 'নিখুঁত মিল', mr: 'उत्तम जुळणी', gu: 'સંપૂર્ણ મેળ', kn: 'ಪರಿಪೂರ್ಣ ಹೊಂದಾಣಿಕೆ', ml: 'തികഞ്ഞ ചേർച്ച', pa: 'ਸੰਪੂਰਨ ਮੇਲ' },
  'eligibility.likely': { en: 'Likely Eligible', hi: 'संभवतः पात्र', ta: 'தகுதி உள்ளது', te: 'అర్హత ఉంది', bn: 'সম্ভবত যোগ্য', mr: 'बहुधा पात्र', gu: 'સંભવતઃ પાત્ર', kn: 'ಅರ್ಹತೆ ಸಾಧ್ಯ', ml: 'യോഗ്യത സാധ്യം', pa: 'ਸੰਭਾਵਿਤ ਯੋਗ' },
  'eligibility.check': { en: 'Check Details', hi: 'जांचें', ta: 'விவரங்களை சரிபார்க்கவும்', te: 'వివరాలు తనిఖీ చేయండి', bn: 'বিস্তারিত দেখুন', mr: 'तपशील पहा', gu: 'વિગતો તપાસો', kn: 'ವಿವರಗಳನ್ನು ಪರಿಶೀಲಿಸಿ', ml: 'വിശദാംശങ്ങൾ പരിശോധിക്കുക', pa: 'ਵੇਰਵੇ ਵੇਖੋ' },
  'eligibility.not_eligible': { en: 'Not Eligible', hi: 'अपात्र', ta: 'தகுதியற்றது', te: 'అనర్హత', bn: 'অযোগ্য', mr: 'अपात्र', gu: 'અપાત્ર', kn: 'ಅನರ್ಹ', ml: 'അയോഗ്യം', pa: 'ਅਯੋਗ' },
  'docs.upload': { en: 'Upload Document', hi: 'दस्तावेज़ अपलोड करें', ta: 'ஆவணத்தை பதிவேற்றவும்', te: 'పత్రం అప్‌లోడ్', bn: 'নথি আপলোড', mr: 'दस्तऐवज अपलोड', gu: 'દસ્તાવેજ અપલોડ', kn: 'ದಾಖಲೆ ಅಪ್‌ಲೋಡ್', ml: 'രേഖ അപ്‌ലോഡ്', pa: 'ਦਸਤਾਵੇਜ਼ ਅੱਪਲੋਡ' },
  'docs.take_photo': { en: 'Take Photo', hi: 'फोटो लें', ta: 'புகைப்படம் எடுக்கவும்', te: 'ఫోటో తీయండి', bn: 'ছবি তুলুন', mr: 'फोटो काढा', gu: 'ફોટો લો', kn: 'ಫೋಟೋ ತೆಗೆಯಿರಿ', ml: 'ഫോട്ടോ എടുക്കുക', pa: 'ਫੋਟੋ ਲਓ' },
  'common.continue': { en: 'Continue', hi: 'जारी रखें', ta: 'தொடரவும்', te: 'కొనసాగించు', bn: 'এগিয়ে যান', mr: 'पुढे चला', gu: 'ચાલુ રાખો', kn: 'ಮುಂದುವರಿಸಿ', ml: 'തുടരുക', pa: 'ਜਾਰੀ ਰੱਖੋ' },
  'common.back': { en: 'Back', hi: 'वापस', ta: 'பின்', te: 'వెనుకకు', bn: 'পিছনে', mr: 'मागे', gu: 'પાછા', kn: 'ಹಿಂದೆ', ml: 'തിരികെ', pa: 'ਪਿੱਛੇ' },
  'common.cancel': { en: 'Cancel', hi: 'रद्द करें', ta: 'ரத்து', te: 'రద్దు', bn: 'বাতিল', mr: 'रद्द करा', gu: 'રદ કરો', kn: 'ರದ್ದು', ml: 'റദ്ദാക്കുക', pa: 'ਰੱਦ ਕਰੋ' },
  'common.retry': { en: 'Retry', hi: 'पुनः प्रयास', ta: 'மீண்டும் முயற்சிக்கவும்', te: 'మళ్ళీ ప్రయత్నించండి', bn: 'আবার চেষ্টা', mr: 'पुन्हा प्रयत्न', gu: 'ફરી પ્રયાસ', kn: 'ಮರುಪ್ರಯತ್ನ', ml: 'വീണ്ടും ശ്രമിക്കുക', pa: 'ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼' },
  'common.save': { en: 'Save', hi: 'सहेजें', ta: 'சேமிக்கவும்', te: 'సేవ్', bn: 'সংরক্ষণ', mr: 'जतन करा', gu: 'સાચવો', kn: 'ಉಳಿಸಿ', ml: 'സേവ്', pa: 'ਸੇਵ' },
  'common.yes': { en: 'Yes', hi: 'हाँ', ta: 'ஆம்', te: 'అవును', bn: 'হ্যাঁ', mr: 'होय', gu: 'હા', kn: 'ಹೌದು', ml: 'അതെ', pa: 'ਹਾਂ' },
  'common.no': { en: 'No', hi: 'नहीं', ta: 'இல்லை', te: 'కాదు', bn: 'না', mr: 'नाही', gu: 'ના', kn: 'ಇಲ್ಲ', ml: 'ഇല്ല', pa: 'ਨਹੀਂ' },
  'common.loading': { en: 'Loading...', hi: 'लोड हो रहा है...', ta: 'ஏற்றுகிறது...', te: 'లోడ్ అవుతోంది...', bn: 'লোড হচ্ছে...', mr: 'लोड होत आहे...', gu: 'લોડ થઈ રહ્યું છે...', kn: 'ಲೋಡ್ ಆಗುತ್ತಿದೆ...', ml: 'ലോഡ് ചെയ്യുന്നു...', pa: 'ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ...' },
  'common.offline': { en: 'You are offline', hi: 'आप ऑफलाइन हैं', ta: 'நீங்கள் ஆஃப்லைனில் உள்ளீர்கள்', te: 'మీరు ఆఫ్‌లైన్‌లో ఉన్నారు', bn: 'আপনি অফলাইনে আছেন', mr: 'तुम्ही ऑफलाइन आहात', gu: 'તમે ઑફલાઇન છો', kn: 'ನೀವು ಆಫ್‌ಲೈನ್‌ನಲ್ಲಿದ್ದೀರಿ', ml: 'നിങ്ങൾ ഓഫ്‌ലൈനിൽ ആണ്', pa: 'ਤੁਸੀਂ ਔਫਲਾਈਨ ਹੋ' },
  'welcome.headline': { en: 'Government schemes made simple', hi: 'सरकारी योजनाएं हुई आसान', ta: 'அரசுத் திட்டங்கள் எளிமையாக', te: 'ప్రభుత్వ పథకాలు సరళంగా', bn: 'সরকারি প্রকল্প সহজ হলো', mr: 'सरकारी योजना सोप्या झाल्या', gu: 'સરકારી યોજનાઓ સરળ બની', kn: 'ಸರ್ಕಾರಿ ಯೋಜನೆಗಳು ಸರಳ', ml: 'സർക്കാർ പദ്ധതികൾ ലളിതമായി', pa: 'ਸਰਕਾਰੀ ਯੋਜਨਾਵਾਂ ਸੌਖੀਆਂ' },
  'welcome.subtitle': { en: 'AI-powered assistance for welfare scheme applications', hi: 'AI-संचालित सहायता कल्याणकारी योजनाओं के लिए', ta: 'நலத்திட்ட விண்ணப்பங்களுக்கு AI உதவி', te: 'సంక్షేమ పథకాలకు AI సహాయం', bn: 'কল্যাণ প্রকল্পের জন্য AI সহায়তা', mr: 'कल्याणकारी योजनांसाठी AI मदत', gu: 'કલ્યાણ યોજનાઓ માટે AI સહાય', kn: 'ಕಲ್ಯಾಣ ಯೋಜನೆಗಳಿಗೆ AI ಸಹಾಯ', ml: 'ക്ഷേമ പദ്ധതികൾക്ക് AI സഹായം', pa: 'ਭਲਾਈ ਯੋਜਨਾਵਾਂ ਲਈ AI ਸਹਾਇਤਾ' },
  'welcome.get_started': { en: 'Get Started', hi: 'शुरू करें', ta: 'தொடங்குங்கள்', te: 'ప్రారంభించండి', bn: 'শুরু করুন', mr: 'सुरू करा', gu: 'શરૂ કરો', kn: 'ಪ್ರಾರಂಭಿಸಿ', ml: 'ആരംഭിക്കുക', pa: 'ਸ਼ੁਰੂ ਕਰੋ' },
  'auth.phone_label': { en: 'Enter your mobile number', hi: 'अपना मोबाइल नंबर दर्ज करें', ta: 'உங்கள் மொபைல் எண்ணை உள்ளிடவும்', te: 'మీ మొబైల్ నంబర్ నమోదు చేయండి', bn: 'আপনার মোবাইল নম্বর দিন', mr: 'तुमचा मोबाइल नंबर टाका', gu: 'તમારો મોબાઈલ નંબર દાખલ કરો', kn: 'ನಿಮ್ಮ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ ನಮೂದಿಸಿ', ml: 'നിങ്ങളുടെ മൊബൈൽ നമ്പർ നൽകുക', pa: 'ਆਪਣਾ ਮੋਬਾਈਲ ਨੰਬਰ ਦਰਜ ਕਰੋ' },
  'auth.continue': { en: 'Continue', hi: 'जारी रखें', ta: 'தொடரவும்', te: 'కొనసాగించండి', bn: 'চালিয়ে যান', mr: 'पुढे जा', gu: 'ચાલુ રાખો', kn: 'ಮುಂದುವರಿಸಿ', ml: 'തുടരുക', pa: 'ਜਾਰੀ ਰੱਖੋ' },
  'auth.trust_message': { en: 'We never share your number', hi: 'हम आपका नंबर कभी साझा नहीं करते', ta: 'நாங்கள் உங்கள் எண்ணை பகிர மாட்டோம்', te: 'మేము మీ నంబర్ ఎప్పటికీ షేర్ చేయము', bn: 'আমরা আপনার নম্বর কখনো শেয়ার করি না', mr: 'आम्ही तुमचा नंबर कधीही शेअर करत नाही', gu: 'અમે તમારો નંબર ક્યારેય શેર કરતા નથી', kn: 'ನಾವು ನಿಮ್ಮ ನಂಬರ್ ಎಂದಿಗೂ ಹಂಚುವುದಿಲ್ಲ', ml: 'ഞങ്ങൾ നിങ്ങളുടെ നമ്പർ ഒരിക്കലും പങ്കിടുകയില്ല', pa: 'ਅਸੀਂ ਤੁਹਾਡਾ ਨੰਬਰ ਕਦੇ ਸਾਂਝਾ ਨਹੀਂ ਕਰਦੇ' },
  'tracking.applied': { en: 'Applied', hi: 'आवेदित', ta: 'விண்ணப்பிக்கப்பட்டது', te: 'దరఖాస్తు చేశారు', bn: 'আবেদিত', mr: 'अर्ज केला', gu: 'અરજી કરી', kn: 'ಅರ್ಜಿ ಸಲ್ಲಿಸಲಾಗಿದೆ', ml: 'അപേക്ഷിച്ചു', pa: 'ਅਰਜ਼ੀ ਦਿੱਤੀ' },
  'tracking.approved': { en: 'Approved', hi: 'स्वीकृत', ta: 'அங்கீகரிக்கப்பட்டது', te: 'ఆమోదించబడింది', bn: 'অনুমোদিত', mr: 'मंजूर', gu: 'મંજૂર', kn: 'ಅನುಮೋದಿಸಲಾಗಿದೆ', ml: 'അനുവദിച്ചു', pa: 'ਮਨਜ਼ੂਰ' },
  'tracking.pending': { en: 'Pending', hi: 'लंबित', ta: 'நிலுவையில்', te: 'పెండింగ్', bn: 'অপেক্ষমান', mr: 'प्रलंबित', gu: 'પેન્ડિંગ', kn: 'ಬಾಕಿ', ml: 'തീർപ്പാകാത', pa: 'ਪੈਂਡਿੰਗ' },
  'tracking.rejected': { en: 'Rejected', hi: 'अस्वीकृत', ta: 'நிராகரிக்கப்பட்டது', te: 'తిరస్కరించబడింది', bn: 'প্রত্যাখ্যাত', mr: 'नाकारलय', gu: 'નકારેલ', kn: 'ತಿರಸ್ಕೃತ', ml: 'നിരസിച്ചു', pa: 'ਰੱਦ' },
  'nav.schemes': { en: 'Schemes', hi: 'योजनाएं', ta: 'திட்டங்கள்', te: 'పథకాలు', bn: 'প্রকল্প', mr: 'योजना', gu: 'યોજનાઓ', kn: 'ಯೋಜನೆಗಳು', ml: 'പദ്ധതികൾ', pa: 'ਯੋਜਨਾਵਾਂ' },
  'home.welcome_back': { en: 'Welcome back', hi: 'स्वागत है', ta: 'மீண்டும் வரவேற்கிறோம்', te: 'తిరిగి స్వాగతం', bn: 'স্বাগতম', mr: 'स्वागत आहे', gu: 'પાછા સ્વાગત', kn: 'ಮರಳಿ ಸ್ವಾಗತ', ml: 'തിരികെ സ്വാഗതം', pa: 'ਵਾਪਸ ਸੁਆਗਤ' },
  'home.services': { en: 'Services', hi: 'सेवाएं', ta: 'சேவைகள்', te: 'సేవలు', bn: 'সেবা', mr: 'सेवा', gu: 'સેવાઓ', kn: 'ಸೇವೆಗಳು', ml: 'സേവനങ്ങൾ', pa: 'ਸੇਵਾਵਾਂ' },
  'home.quick_links': { en: 'Quick Links', hi: 'त्वरित लिंक', ta: 'விரைவு இணைப்புகள்', te: 'త్వరిత లింకులు', bn: 'দ্রুত লিংক', mr: 'जलद दुवे', gu: 'ઝડપી લિંક્સ', kn: 'ತ್ವರಿತ ಲಿಂಕ್‌ಗಳು', ml: 'ദ്രുത ലിങ്കുകൾ', pa: 'ਤੇਜ਼ ਲਿੰਕ' },
  'home.search_placeholder': { en: 'Search services, schemes, documents...', hi: 'सेवाएं, योजनाएं, दस्तावेज़ खोजें...', ta: 'சேவைகள், திட்டங்கள், ஆவணங்களை தேடுங்கள்...', te: 'సేవలు, పథకాలు, పత్రాలు వెతకండి...', bn: 'সেবা, প্রকল্প, নথি অনুসন্ধান...', mr: 'सेवा, योजना, दस्तऐवज शोधा...', gu: 'સેવાઓ, યોજનાઓ, દસ્તાવેજો શોધો...', kn: 'ಸೇವೆಗಳು, ಯೋಜನೆಗಳು, ದಾಖಲೆಗಳನ್ನು ಹುಡುಕಿ...', ml: 'സേവനങ്ങൾ, പദ്ധതികൾ, രേഖകൾ തിരയുക...', pa: 'ਸੇਵਾਵਾਂ, ਯੋਜਨਾਵਾਂ, ਦਸਤਾਵੇਜ਼ ਖੋਜੋ...' },
  'home.recommended_schemes': { en: 'Recommended Schemes', hi: 'अनुशंसित योजनाएं', ta: 'பரிந்துரைக்கப்பட்ட திட்டங்கள்', te: 'సిఫార్సు చేసిన పథకాలు', bn: 'প্রস্তাবিত প্রকল্প', mr: 'शिफारस केलेल्या योजना', gu: 'ભલામણ કરેલ યોજનાઓ', kn: 'ಶಿಫಾರಸು ಮಾಡಿದ ಯೋಜನೆಗಳು', ml: 'ശുപാർശ ചെയ്ത പദ്ധതികൾ', pa: 'ਸਿਫ਼ਾਰਸ਼ੀ ਯੋਜਨਾਵਾਂ' },
  'home.view_all': { en: 'View All', hi: 'सभी देखें', ta: 'அனைத்தும் காண்க', te: 'అన్నీ చూడండి', bn: 'সব দেখুন', mr: 'सर्व पहा', gu: 'બધા જુઓ', kn: 'ಎಲ್ಲಾ ನೋಡಿ', ml: 'എല്ലാം കാണുക', pa: 'ਸਭ ਵੇਖੋ' },
  'schemes.government_schemes': { en: 'Government Schemes', hi: 'सरकारी योजनाएं', ta: 'அரசுத் திட்டங்கள்', te: 'ప్రభుత్వ పథకాలు', bn: 'সরকারি প্রকল্প', mr: 'सरकारी योजना', gu: 'સરકારી યોજનાઓ', kn: 'ಸರ್ಕಾರಿ ಯೋಜನೆಗಳು', ml: 'സർക്കാർ പദ്ധതികൾ', pa: 'ਸਰਕਾਰੀ ਯੋਜਨਾਵਾਂ' },
  'schemes.total': { en: 'Total', hi: 'कुल', ta: 'மொத்தம்', te: 'మొత్తం', bn: 'মোট', mr: 'एकूण', gu: 'કુલ', kn: 'ಒಟ್ಟು', ml: 'ആകെ', pa: 'ਕੁੱਲ' },
  'schemes.eligible': { en: 'Eligible', hi: 'पात्र', ta: 'தகுதி', te: 'అర్హత', bn: 'যোগ্য', mr: 'पात्र', gu: 'પાત્ર', kn: 'ಅರ್ಹ', ml: 'യോഗ്യം', pa: 'ਯੋਗ' },
  'schemes.applied': { en: 'Applied', hi: 'आवेदित', ta: 'விண்ணப்பிக்கப்பட்டது', te: 'దరఖాస్తు చేశారు', bn: 'আবেদিত', mr: 'अर्ज केला', gu: 'અરજી કરી', kn: 'ಅರ್ಜಿ ಸಲ್ಲಿಸಲಾಗಿದೆ', ml: 'അപേക്ഷിച്ചു', pa: 'ਅਰਜ਼ੀ ਦਿੱਤੀ' },
  'schemes.all_schemes': { en: 'All Schemes', hi: 'सभी योजनाएं', ta: 'அனைத்து திட்டங்கள்', te: 'అన్ని పథకాలు', bn: 'সকল প্রকল্প', mr: 'सर्व योजना', gu: 'બધી યોજનાઓ', kn: 'ಎಲ್ಲಾ ಯೋಜನೆಗಳು', ml: 'എല്ലാ പദ്ധതികളും', pa: 'ਸਾਰੀਆਂ ਯੋਜਨਾਵਾਂ' },
  'schemes.eligible_for_you': { en: 'Eligible For You', hi: 'आपके लिए पात्र', ta: 'உங்களுக்கு தகுதி', te: 'మీ కోసం అర్హత', bn: 'আপনার জন্য যোগ্য', mr: 'तुमच्यासाठी पात्र', gu: 'તમારા માટે પાત્ર', kn: 'ನಿಮಗೆ ಅರ್ಹ', ml: 'നിങ്ങൾക്ക് യോഗ്യം', pa: 'ਤੁਹਾਡੇ ਲਈ ਯੋਗ' },
  'schemes.no_schemes': { en: 'No schemes found', hi: 'कोई योजना नहीं मिली', ta: 'திட்டங்கள் இல்லை', te: 'పథకాలు కనుగొనబడలేదు', bn: 'কোনো প্রকল্প পাওয়া যায়নি', mr: 'योजना सापडल्या नाहीत', gu: 'કોઈ યોજના મળી નથી', kn: 'ಯೋಜನೆಗಳು ಕಂಡುಬಂದಿಲ್ಲ', ml: 'പദ്ധതികൾ കണ്ടെത്തിയില്ല', pa: 'ਕੋਈ ਯੋਜਨਾ ਨਹੀਂ ਮਿਲੀ' },
  'schemes.load_more': { en: 'Load More Schemes', hi: 'और योजनाएं लोड करें', ta: 'மேலும் திட்டங்களைக் காண்க', te: 'మరిన్ని పథకాలు లోడ్ చేయండి', bn: 'আরও প্রকল্প লোড করুন', mr: 'अधिक योजना लोड करा', gu: 'વધુ યોજનાઓ લોડ કરો', kn: 'ಹೆಚ್ಚಿನ ಯೋಜನೆಗಳನ್ನು ಲೋಡ್ ಮಾಡಿ', ml: 'കൂടുതൽ പദ്ധതികൾ ലോഡ് ചെയ്യുക', pa: 'ਹੋਰ ਯੋਜਨਾਵਾਂ ਲੋਡ ਕਰੋ' },
  'schemes.apply_with_ai': { en: 'Apply with AI', hi: 'AI से आवेदन', ta: 'AI மூலம் விண்ணப்பிக்கவும்', te: 'AI తో దరఖాస్తు', bn: 'AI দিয়ে আবেদন', mr: 'AI ने अर्ज करा', gu: 'AI થી અરજી', kn: 'AI ಮೂಲಕ ಅರ್ಜಿ', ml: 'AI വഴി അപേക്ഷിക്കുക', pa: 'AI ਨਾਲ ਅਰਜ਼ੀ' },
  'schemes.view_more': { en: 'View More', hi: 'और देखें', ta: 'மேலும் காண்க', te: 'మరింత చూడండి', bn: 'আরও দেখুন', mr: 'अधिक पहा', gu: 'વધુ જુઓ', kn: 'ಇನ್ನಷ್ಟು ನೋಡಿ', ml: 'കൂടുതൽ കാണുക', pa: 'ਹੋਰ ਵੇਖੋ' },
  'schemes.less': { en: 'Less', hi: 'कम', ta: 'குறைவாக', te: 'తక్కువ', bn: 'কম', mr: 'कमी', gu: 'ઓછું', kn: 'ಕಡಿಮೆ', ml: 'കുറവ്', pa: 'ਘੱਟ' },
  'schemes.showing': { en: 'Showing', hi: 'दिखा रहे हैं', ta: 'காட்டுகிறது', te: 'చూపిస్తోంది', bn: 'দেখাচ্ছে', mr: 'दाखवत आहे', gu: 'બતાવી રહ્યું છે', kn: 'ತೋರಿಸುತ್ತಿದೆ', ml: 'കാണിക്കുന്നു', pa: 'ਦਿਖਾ ਰਿਹਾ ਹੈ' },
  'schemes.of': { en: 'of', hi: 'में से', ta: 'இல்', te: 'లో', bn: 'এর মধ্যে', mr: 'पैकी', gu: 'માંથી', kn: 'ರಲ್ಲಿ', ml: 'ൽ', pa: 'ਵਿੱਚੋਂ' },
  'schemes.remaining': { en: 'remaining', hi: 'शेष', ta: 'மீதமுள்ள', te: 'మిగిలిన', bn: 'অবশিষ্ট', mr: 'उर्वरित', gu: 'બાકી', kn: 'ಉಳಿದ', ml: 'ശേഷിക്കുന്ന', pa: 'ਬਾਕੀ' },
  'docs.documents': { en: 'Documents', hi: 'दस्तावेज़', ta: 'ஆவணங்கள்', te: 'పత్రాలు', bn: 'নথিপত্র', mr: 'दस्तऐवज', gu: 'દસ્તાવેજો', kn: 'ದಾಖಲೆಗಳು', ml: 'രേഖകൾ', pa: 'ਦਸਤਾਵੇਜ਼' },
  'docs.upload_new': { en: 'Upload New', hi: 'नया अपलोड', ta: 'புதியதை பதிவேற்றவும்', te: 'కొత్తది అప్‌లోడ్', bn: 'নতুন আপলোড', mr: 'नवीन अपलोड', gu: 'નવું અપલોડ', kn: 'ಹೊಸ ಅಪ್‌ಲೋಡ್', ml: 'പുതിയത് അപ്‌ലോഡ്', pa: 'ਨਵਾਂ ਅੱਪਲੋਡ' },
  'notifications.title': { en: 'Notifications', hi: 'सूचनाएं', ta: 'அறிவிப்புகள்', te: 'నోటిఫికేషన్లు', bn: 'বিজ্ঞপ্তি', mr: 'सूचना', gu: 'સૂચનાઓ', kn: 'ಅಧಿಸೂಚನೆಗಳು', ml: 'അറിയിപ്പുകൾ', pa: 'ਸੂਚਨਾਵਾਂ' },
  'notifications.mark_all_read': { en: 'Mark all as read', hi: 'सभी पढ़ा हुआ चिह्नित करें', ta: 'அனைத்தையும் படிக்கப்பட்டதாகக் குறிக்கவும்', te: 'అన్నీ చదివినట్లు గుర్తించండి', bn: 'সব পঠিত হিসেবে চিহ্নিত করুন', mr: 'सर्व वाचले म्हणून चिन्हांकित करा', gu: 'બધાને વાંચેલ તરીકે ચિહ્નિત કરો', kn: 'ಎಲ್ಲವನ್ನೂ ಓದಿದೆ ಎಂದು ಗುರುತಿಸಿ', ml: 'എല്ലാം വായിച്ചതായി അടയാളപ്പെടുത്തുക', pa: 'ਸਭ ਪੜ੍ਹਿਆ ਮਾਰਕ ਕਰੋ' },
  'lang.select_language': { en: 'Select Language', hi: 'भाषा चुनें', ta: 'மொழியைத் தேர்ந்தெடுக்கவும்', te: 'భాషను ఎంచుకోండి', bn: 'ভাষা নির্বাচন', mr: 'भाषा निवडा', gu: 'ભાષા પસંદ કરો', kn: 'ಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ', ml: 'ഭാഷ തിരഞ്ഞെടുക്കുക', pa: 'ਭਾਸ਼ਾ ਚੁਣੋ' },
  'header.tagline': { en: 'The Spirit of New India', hi: 'नये भारत की भावना', ta: 'புதிய இந்தியாவின் உணர்வு', te: 'కొత్త భారతదేశ స్ఫూర్తి', bn: 'নতুন ভারতের মনোভাব', mr: 'नव्या भारताची भावना', gu: 'નવા ભારતની ભાવના', kn: 'ಹೊಸ ಭಾರತದ ಸ್ಫೂರ್ತಿ', ml: 'പുതിയ ഇന്ത്യയുടെ ചൈതന്യം', pa: 'ਨਵੇਂ ਭਾਰਤ ਦੀ ਭਾਵਨਾ' },
  'home.check_eligibility': { en: 'Check Eligibility', hi: 'पात्रता जांचें', ta: 'தகுதியை சரிபார்க்கவும்', te: 'అర్హత తనిఖీ చేయండి', bn: 'যোগ্যতা পরীক্ষা', mr: 'पात्रता तपासा', gu: 'પાત્રતા તપાસો', kn: 'ಅರ್ಹತೆ ಪರಿಶೀಲಿಸಿ', ml: 'യോഗ്യത പരിശോധിക്കുക', pa: 'ਯੋਗਤਾ ਜਾਂਚੋ' },
  'home.track_application': { en: 'Track Application', hi: 'आवेदन ट्रैक करें', ta: 'விண்ணப்பத்தை கண்காணிக்கவும்', te: 'దరఖాస్తు ట్రాక్ చేయండి', bn: 'আবেদন ট্র্যাক', mr: 'अर्ज ट्रॅक करा', gu: 'અરજી ટ્રેક કરો', kn: 'ಅರ್ಜಿ ಟ್ರ್ಯಾಕ್ ಮಾಡಿ', ml: 'അപേക്ഷ ട്രാക്ക് ചെയ്യുക', pa: 'ਅਰਜ਼ੀ ਟ੍ਰੈਕ ਕਰੋ' },
  'cat.health': { en: 'Health', hi: 'स्वास्थ्य', ta: 'சுகாதாரம்', te: 'ఆరోగ్యం', bn: 'স্বাস্থ্য', mr: 'आरोग्य', gu: 'આરોગ્ય', kn: 'ಆರೋಗ್ಯ', ml: 'ആരോഗ്യം', pa: 'ਸਿਹਤ' },
  'cat.education': { en: 'Education', hi: 'शिक्षा', ta: 'கல்வி', te: 'విద్య', bn: 'শিক্ষা', mr: 'शिक्षण', gu: 'શિક્ષણ', kn: 'ಶಿಕ್ಷಣ', ml: 'വിദ്യാഭ്യാസം', pa: 'ਸਿੱਖਿਆ' },
  'cat.agriculture': { en: 'Agriculture', hi: 'कृषि', ta: 'வேளாண்மை', te: 'వ్యవసాయం', bn: 'কৃষি', mr: 'कृषी', gu: 'કૃષિ', kn: 'ಕೃಷಿ', ml: 'കൃഷി', pa: 'ਖੇਤੀ' },
  'cat.housing': { en: 'Housing', hi: 'आवास', ta: 'வீட்டுவசதி', te: 'గృహనిర్మాణం', bn: 'আবাসন', mr: 'गृहनिर्माण', gu: 'આવાસ', kn: 'ವಸತಿ', ml: 'ഭവനം', pa: 'ਮਕਾਨ' },
  'cat.pension': { en: 'Pension', hi: 'पेंशन', ta: 'ஓய்வூதியம்', te: 'పెన్షన్', bn: 'পেনশন', mr: 'पेन्शन', gu: 'પેન્શન', kn: 'ಪಿಂಚಣಿ', ml: 'പെൻഷൻ', pa: 'ਪੈਨਸ਼ਨ' },
  'cat.welfare': { en: 'Welfare', hi: 'कल्याण', ta: 'நலன்புரி', te: 'సంక్షేమం', bn: 'কল্যাণ', mr: 'कल्याण', gu: 'કલ્યાણ', kn: 'ಕಲ್ಯಾಣ', ml: 'ക്ഷേമം', pa: 'ਭਲਾਈ' },
  'cat.finance': { en: 'Finance', hi: 'वित्त', ta: 'நிதி', te: 'ఆర్థికం', bn: 'অর্থ', mr: 'वित्त', gu: 'નાણાં', kn: 'ಹಣಕಾಸು', ml: 'ധനകാര്യം', pa: 'ਵਿੱਤ' },
  'cat.employment': { en: 'Employment', hi: 'रोजगार', ta: 'வேலைவாய்ப்பு', te: 'ఉద్యోగం', bn: 'কর্মসংস্থান', mr: 'रोजगार', gu: 'રોજગાર', kn: 'ಉದ್ಯೋಗ', ml: 'തൊഴിൽ', pa: 'ਰੁਜ਼ਗਾਰ' },
  'cat.women_child': { en: 'Women & Child', hi: 'महिला एवं बाल', ta: 'பெண்கள் & குழந்தைகள்', te: 'మహిళా & శిశు', bn: 'মহিলা ও শিশু', mr: 'महिला व बालक', gu: 'મહિલા અને બાળ', kn: 'ಮಹಿಳಾ ಮತ್ತು ಮಕ್ಕಳ', ml: 'വനിതാ & ശിശു', pa: 'ਔਰਤ ਅਤੇ ਬੱਚੇ' },
  'cat.women': { en: 'Women & Child', hi: 'महिला एवं बाल', ta: 'பெண்கள் & குழந்தைகள்', te: 'మహిళా & శిశు', bn: 'মহিলা ও শিশু', mr: 'महिला व बालक', gu: 'મહિલા અને બાળ', kn: 'ಮಹಿಳಾ ಮತ್ತು ಮಕ್ಕಳ', ml: 'വനിതാ & ശിശു', pa: 'ਔਰਤ ਅਤੇ ਬੱਚੇ' },
  'cat.legal': { en: 'Legal Aid', hi: 'कानूनी सहायता', ta: 'சட்ட உதவி', te: 'న్యాయ సహాయం', bn: 'আইনি সহায়তা', mr: 'कायदेशीर मदत', gu: 'કાનૂની સહાય', kn: 'ಕಾನೂನು ನೆರವು', ml: 'നിയമ സഹായം', pa: 'ਕਾਨੂੰਨੀ ਸਹਾਇਤਾ' },
  'cat.travel': { en: 'Travel', hi: 'यात्रा', ta: 'பயணம்', te: 'ప్రయాణం', bn: 'ভ্রমণ', mr: 'प्रवास', gu: 'મુસાફરી', kn: 'ಪ್ರಯಾಣ', ml: 'യാത്ര', pa: 'ਯਾਤਰਾ' },
  'cat.utilities': { en: 'Utilities', hi: 'उपयोगिताएं', ta: 'பயன்பாடுகள்', te: 'యుటిలిటీలు', bn: 'ইউটিলিটি', mr: 'उपयोगिता', gu: 'ઉપયોગિતાઓ', kn: 'ಉಪಯುಕ್ತತೆಗಳು', ml: 'യൂട്ടിലിറ്റികൾ', pa: 'ਸਹੂਲਤਾਂ' },
  'schemes.schemes_from_tn': { en: 'schemes from Tamil Nadu', hi: 'तमिलनाडु की योजनाएं', ta: 'தமிழ்நாடு திட்டங்கள்', te: 'తమిళనాడు పథకాలు', bn: 'তামিলনাড়ু প্রকল্প', mr: 'तामिळनाडू योजना', gu: 'તમિલનાડુ યોજનાઓ', kn: 'ತಮಿಳುನಾಡು ಯೋಜನೆಗಳು', ml: 'തമിഴ്‌നാട് പദ്ധതികൾ', pa: 'ਤਾਮਿਲਨਾਡੂ ਯੋਜਨਾਵਾਂ' },
  'schemes.eligible_banner_title': { en: 'Schemes You\'re Eligible For', hi: 'जिन योजनाओं के लिए आप पात्र हैं', ta: 'நீங்கள் தகுதியான திட்டங்கள்', te: 'మీకు అర్హత ఉన్న పథకాలు', bn: 'আপনার জন্য যোগ্য প্রকল্প', mr: 'तुम्ही पात्र असलेल्या योजना', gu: 'તમે પાત્ર છો તે યોજનાઓ', kn: 'ನೀವು ಅರ್ಹರಾಗಿರುವ ಯೋಜನೆಗಳು', ml: 'നിങ്ങൾ യോഗ്യരായ പദ്ധതികൾ', pa: 'ਤੁਸੀਂ ਯੋਗ ਹੋ ਉਹ ਯੋਜਨਾਵਾਂ' },
  'common.apply_now': { en: 'Apply Now', hi: 'अभी आवेदन करें', ta: 'இப்போது விண்ணப்பிக்கவும்', te: 'ఇప్పుడు దరఖాస్తు చేయండి', bn: 'এখনই আবেদন করুন', mr: 'आता अर्ज करा', gu: 'હવે અરજી કરો', kn: 'ಈಗ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ', ml: 'ഇപ്പോൾ അപേക്ഷിക്കുക', pa: 'ਹੁਣੇ ਅਰਜ਼ੀ ਦਿਓ' },
  'footer.quick_links': { en: 'Quick Links', hi: 'त्वरित लिंक', ta: 'விரைவு இணைப்புகள்', te: 'త్వరిత లింకులు', bn: 'দ্রুত লিংক', mr: 'जलद दुवे', gu: 'ઝડપી લિંક્સ', kn: 'ತ್ವರಿತ ಲಿಂಕ್‌ಗಳು', ml: 'ദ്രുത ലിങ്കുകൾ', pa: 'ਤੇਜ਼ ਲਿੰਕ' },
  'footer.contact_us': { en: 'Contact Us', hi: 'संपर्क करें', ta: 'எங்களை தொடர்புகொள்ளுங்கள்', te: 'మమ్మల్ని సంప్రదించండి', bn: 'যোগাযোগ করুন', mr: 'आमच्याशी संपर्क साधा', gu: 'અમારો સંપર્ક', kn: 'ನಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸಿ', ml: 'ഞങ്ങളെ ബന്ധപ്പെടുക', pa: 'ਸਾਡੇ ਨਾਲ ਸੰਪਰਕ ਕਰੋ' },
};

// ============================================================
// Demo Mode Data
// ============================================================
export const DEMO_SCHEMES: Scheme[] = [
  {
    id: 'pm-kisan',
    name: 'PM-KISAN Samman Nidhi',
    nameHi: 'पीएम-किसान सम्मान निधि',
    description: 'Income support of ₹6,000 per year in three installments to all farmer families.',
    descriptionHi: 'सभी किसान परिवारों को तीन किस्तों में ₹6,000 प्रति वर्ष की आय सहायता।',
    category: 'agriculture',
    benefitAmount: 6000,
    benefitFrequency: 'yearly',
    eligibilityScore: 95,
    requiredDocuments: ['aadhaar', 'bank_passbook'],
    deadline: '2026-03-31',
    successRate: 92,
    ministry: 'Ministry of Agriculture',
    applicationUrl: 'https://pmkisan.gov.in',
    tags: ['farmer', 'income-support', 'direct-benefit'],
  },
  {
    id: 'pm-scholarship',
    name: 'PM Scholarship Scheme',
    nameHi: 'पीएम छात्रवृत्ति योजना',
    description: 'Scholarship for dependent wards of ex-servicemen and ex-coast guard personnel.',
    descriptionHi: 'पूर्व सैनिकों और पूर्व तटरक्षक कर्मियों के आश्रित वार्डों के लिए छात्रवृत्ति।',
    category: 'education',
    benefitAmount: 36000,
    benefitFrequency: 'yearly',
    eligibilityScore: 78,
    requiredDocuments: ['aadhaar', 'marksheet', 'bank_passbook', 'income_cert'],
    deadline: '2026-06-30',
    successRate: 85,
    ministry: 'Ministry of Defence',
    applicationUrl: 'https://scholarships.gov.in',
    tags: ['education', 'scholarship', 'student'],
  },
  {
    id: 'ayushman-bharat',
    name: 'Ayushman Bharat - PMJAY',
    nameHi: 'आयुष्मान भारत - पीएमजेएवाई',
    description: 'Health insurance cover of ₹5 lakh per family per year for secondary and tertiary care hospitalization.',
    descriptionHi: 'माध्यमिक और तृतीयक देखभाल अस्पताल में ₹5 लाख प्रति परिवार प्रति वर्ष स्वास्थ्य बीमा कवर।',
    category: 'health',
    benefitAmount: 500000,
    benefitFrequency: 'yearly',
    eligibilityScore: 88,
    requiredDocuments: ['aadhaar', 'ration_card'],
    successRate: 90,
    ministry: 'Ministry of Health',
    applicationUrl: 'https://pmjay.gov.in',
    tags: ['health', 'insurance', 'hospital'],
  },
  {
    id: 'pm-awas',
    name: 'PM Awas Yojana',
    nameHi: 'पीएम आवास योजना',
    description: 'Financial assistance for construction of pucca houses for eligible rural households.',
    descriptionHi: 'पात्र ग्रामीण परिवारों को पक्के मकान बनाने के लिए वित्तीय सहायता।',
    category: 'housing',
    benefitAmount: 120000,
    benefitFrequency: 'one-time',
    eligibilityScore: 65,
    requiredDocuments: ['aadhaar', 'income_cert', 'domicile', 'bank_passbook'],
    successRate: 75,
    ministry: 'Ministry of Housing',
    applicationUrl: 'https://pmayg.nic.in',
    tags: ['housing', 'construction', 'rural'],
  },
  {
    id: 'widow-pension',
    name: 'Indira Gandhi Widow Pension',
    nameHi: 'इंदिरा गांधी विधवा पेंशन',
    description: 'Monthly pension of ₹300 for widows between 40-79 years from BPL families.',
    descriptionHi: 'BPL परिवारों की 40-79 वर्ष की विधवाओं को ₹300 मासिक पेंशन।',
    category: 'pension',
    benefitAmount: 3600,
    benefitFrequency: 'yearly',
    eligibilityScore: 42,
    requiredDocuments: ['aadhaar', 'voter_id', 'income_cert', 'bank_passbook'],
    successRate: 80,
    ministry: 'Ministry of Rural Development',
    applicationUrl: 'https://nsap.nic.in',
    tags: ['pension', 'widow', 'social-security'],
  },
  {
    id: 'sukanya',
    name: 'Sukanya Samriddhi Yojana',
    nameHi: 'सुकन्या समृद्धि योजना',
    description: 'Savings scheme for girl child with attractive interest rate and tax benefits.',
    descriptionHi: 'बालिकाओं के लिए आकर्षक ब्याज दर और कर लाभ वाली बचत योजना।',
    category: 'welfare',
    benefitAmount: 250000,
    benefitFrequency: 'one-time',
    eligibilityScore: 91,
    requiredDocuments: ['aadhaar', 'pan', 'photo'],
    successRate: 95,
    ministry: 'Ministry of Finance',
    applicationUrl: 'https://www.india.gov.in',
    tags: ['girl-child', 'savings', 'investment'],
  },
];

// ============================================================
// Import Scheme type
// ============================================================
import type { Scheme } from '@/types';
